version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prom_data:/prometheus
    networks:
      prod_semesta:
        ipv4_address: 10.0.0.2
volumes:
  prom_data: {}

networks:
  prod_semesta:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
