# handlers file for prod_semesta
- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: start and enable nginx
  service:
    name: docker
    state: started
    enabled: yes

- name: update package list
  apt:
    update_cache: yes

- name: create docker network
  shell:
    cmd: docker network create --subnet=10.0.0.0/29 --gateway=10.0.0.1 prod_semesta
