version: "3.9"

services:
  ansible_control:
    image: alpinelinux/ansible
    container_name: ansible_control
    restart: unless-stopped
    tty: true
    volumes:
      - ./config:/etc/ansible
      - ~/.ssh:/root/.ssh:ro
    networks:
      dev_semesta:
        ipv4_address: 192.168.1.2

networks:
  dev_semesta:
    external: true