version: "3.9"
services:
  jenkins_server:
    container_name: jenkins_server
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
    networks:
      dev_semesta:
        ipv4_address: 192.168.1.3

networks:
  dev_semesta:
    external: true
volumes:
  jenkins-home: {}
